// SPDX-License-Identifier: MIT
// Sourcepad — file-extension to Lexilla-lexer mapping.
// AUTO-GENERATED by scripts/extract-langs.py. Do not edit by hand.
//
// Sources (factual data only, no copyrighted expression copied):
//   - Notepad++ langs.model.xml                       (extension lists)
//   - Notepad++ ScintillaEditView.cpp _langNameInfoArray (langname→lexerId)
//   - Curated VS Code language metadata               (modern langs)

import Foundation

public enum LexerRegistry {
    /// File extension (lowercased, no dot) → Lexilla lexer name.
    /// `nil` means "no syntax highlighting" (plain text).
    public static let byExtension: [String: String?] = [
        "ada": "ada",   // ada
        "adb": "ada",   // ada
        "ads": "ada",   // ada
        "as": "cpp",   // actionscript
        "asm": "asm",   // asm
        "asp": "hypertext",   // asp
        "aspx": "hypertext",   // asp
        "astro": "hypertext",   // astro
        "au3": "au3",   // autoit
        "avs": "avs",   // avs
        "avsi": "avs",   // avs
        "bas": "freebasic",   // freebasic
        "bash": "bash",   // bash
        "bash_profile": "bash",   // bash
        "bashrc": "bash",   // bash
        "bat": "batch",   // batch
        "bb": "blitzbasic",   // blitzbasic
        "bc": "baan",   // baanc
        "bi": "freebasic",   // freebasic
        "blade.php": "hypertext",   // blade
        "bsh": "bash",   // bash
        "c": "cpp",   // c
        "cbd": "COBOL",   // cobol
        "cbl": "COBOL",   // cobol
        "cc": "cpp",   // cpp
        "cdb": "COBOL",   // cobol
        "cdc": "COBOL",   // cobol
        "cf": "props",   // props
        "cfg": "props",   // props
        "cl": "visualprolog",   // visualprolog
        "clj": "lisp",   // clojure
        "cljc": "lisp",   // clojure
        "cljs": "lisp",   // clojure
        "cln": "baan",   // baanc
        "cmake": "cmake",   // cmake
        "cmd": "batch",   // batch
        "cob": "COBOL",   // cobol
        "coffee": "coffeescript",   // coffeescript
        "command": "bash",   // shellscript
        "commit_editmsg": nil,   // gitcommit
        "conf": "props",   // props
        "copy": "COBOL",   // cobol
        "cpp": "cpp",   // cpp
        "cpy": "COBOL",   // cobol
        "cr": "ruby",   // crystal
        "cs": "cpp",   // cs
        "csd": "csound",   // csound
        "csh": "bash",   // bash
        "csproj": "xml",   // xml
        "css": "css",   // css
        "csv": nil,   // csv
        "csxproj": "xml",   // xml
        "cts": "cpp",   // typescript
        "cxx": "cpp",   // cpp
        "d": "d",   // d
        "dart": "cpp",   // dart
        "dbproj": "xml",   // xml
        "diff": "diff",   // diff
        "dockerfile": "bash",   // dockerfile
        "dpr": "pascal",   // pascal
        "dproj": "xml",   // xml
        "editorconfig": "props",   // props
        "edn": "lisp",   // clojure
        "ejs": "hypertext",   // ejs
        "elm": "haskell",   // elm
        "em": "escript",   // escript
        "env": "bash",   // dotenv
        "erl": "erlang",   // erlang
        "err": "errorlist",   // errorlist
        "ex": "cpp",   // elixir
        "exs": "cpp",   // elixir
        "f": "fortran",   // fortran
        "f23": "fortran",   // fortran
        "f2k": "fortran",   // fortran
        "f77": "f77",   // fortran77
        "f90": "fortran",   // fortran
        "f95": "fortran",   // fortran
        "fish": "bash",   // fish
        "for": "fortran",   // fortran
        "forth": "forth",   // forth
        "fs": "caml",   // fsharp
        "fsi": "caml",   // fsharp
        "fsscript": "caml",   // fsharp
        "fsx": "caml",   // fsharp
        "gd": "gdscript",   // gdscript
        "gitattributes": "props",   // props
        "gitconfig": "props",   // props
        "gitignore": "bash",   // gitignore
        "gitmodules": "props",   // props
        "gml": "xml",   // xml
        "go": "cpp",   // go
        "gpx": "xml",   // xml
        "gql": "cpp",   // graphql
        "graphql": "cpp",   // graphql
        "graphqls": "cpp",   // graphql
        "groovy": "cpp",   // groovy
        "gui": "gui4cli",   // gui4cli
        "gvy": "cpp",   // groovy
        "h": "cpp",   // cpp
        "handlebars": "hypertext",   // handlebars
        "hbs": "hypertext",   // handlebars
        "hex": "ihex",   // ihex
        "hh": "cpp",   // cpp
        "hpp": "cpp",   // cpp
        "hrl": "erlang",   // erlang
        "hs": "haskell",   // haskell
        "hta": "hypertext",   // html
        "htm": "hypertext",   // html
        "html": "hypertext",   // html
        "html.hbs": "hypertext",   // html.handlebars
        "hws": "hollywood",   // hollywood
        "hxx": "cpp",   // cpp
        "i": "visualprolog",   // visualprolog
        "inc": "pascal",   // pascal
        "inf": "props",   // ini
        "ini": "props",   // ini
        "ino": "cpp",   // cpp
        "iss": "inno",   // inno
        "itcl": "tcl",   // tcl
        "j2": "hypertext",   // jinja
        "jade": "html",   // pug
        "java": "cpp",   // java
        "jinja": "hypertext",   // jinja
        "jinja2": "hypertext",   // jinja
        "jl": "julia",   // julia
        "js": "cpp",   // javascript.js
        "jsm": "cpp",   // javascript.js
        "json": "json",   // json
        "json5": "json",   // json5
        "jsonc": "json",   // json5
        "jsp": "hypertext",   // jsp
        "jsx": "cpp",   // javascript.js
        "kix": "kix",   // kix
        "kml": "xml",   // xml
        "kt": "cpp",   // kotlin
        "kts": "cpp",   // kotlin
        "las": "haskell",   // haskell
        "less": "css",   // less
        "lex": "cpp",   // c
        "lhs": "haskell",   // haskell
        "lisp": "lisp",   // lisp
        "litcoffee": "coffeescript",   // coffeescript
        "lpr": "pascal",   // pascal
        "lsp": "lisp",   // lisp
        "lst": "COBOL",   // cobol
        "lua": "lua",   // lua
        "m": "matlab",   // matlab
        "mak": "makefile",   // makefile
        "mdx": "markdown",   // mdx
        "mib": "asn1",   // asn1
        "mjs": "cpp",   // javascript.js
        "mk": "makefile",   // makefile
        "ml": "caml",   // caml
        "mli": "caml",   // caml
        "mm": "objc",   // objc
        "mms": "mmixal",   // mmixal
        "mot": "srec",   // srec
        "mts": "cpp",   // typescript
        "mustache": "hypertext",   // handlebars
        "mx": "cpp",   // actionscript
        "mxml": "xml",   // xml
        "nfo": nil,   // nfo
        "nim": "nimrod",   // nim
        "nsh": "nsis",   // nsis
        "nsi": "nsis",   // nsis
        "nt": "batch",   // batch
        "orc": "csound",   // csound
        "osx": "oscript",   // oscript
        "out": "spice",   // spice
        "p": "pascal",   // pascal
        "p6": "raku",   // raku
        "pack": "visualprolog",   // visualprolog
        "pas": "pascal",   // pascal
        "patch": "diff",   // diff
        "pb": "purebasic",   // purebasic
        "ph": "visualprolog",   // visualprolog
        "php": "phpscript",   // php
        "php3": "phpscript",   // php
        "php4": "phpscript",   // php
        "php5": "phpscript",   // php
        "phps": "phpscript",   // php
        "phpt": "phpscript",   // php
        "phtml": "phpscript",   // php
        "pl": "perl",   // perl
        "plist": "xml",   // xml
        "plx": "perl",   // perl
        "pm": "perl",   // perl
        "pm6": "raku",   // raku
        "pod6": "raku",   // raku
        "pp": "pascal",   // pascal
        "pro": "visualprolog",   // visualprolog
        "profile": "bash",   // bash
        "properties": "props",   // props
        "ps": "ps",   // postscript
        "ps1": "powershell",   // powershell
        "psd1": "powershell",   // powershell
        "psm1": "powershell",   // powershell
        "pug": "html",   // pug
        "pxd": "python",   // python
        "pxi": "python",   // python
        "py": "python",   // python
        "pyi": "python",   // python
        "pyw": "python",   // python
        "pyx": "python",   // python
        "r": "r",   // r
        "r2": "rebol",   // rebol
        "r3": "rebol",   // rebol
        "raku": "raku",   // raku
        "rakudoc": "raku",   // raku
        "rakumod": "raku",   // raku
        "rakutest": "raku",   // raku
        "rb": "ruby",   // ruby
        "rbw": "ruby",   // ruby
        "rc": "cpp",   // rc
        "reb": "rebol",   // rebol
        "reg": "registry",   // registry
        "rs": "rust",   // rust
        "s": "r",   // r
        "sas": "sas",   // sas
        "sass": "css",   // sass
        "sc": "cpp",   // scala
        "scala": "cpp",   // scala
        "scm": "lisp",   // scheme
        "sco": "csound",   // csound
        "scp": "spice",   // spice
        "scss": "css",   // scss
        "sh": "bash",   // bash
        "shtm": "hypertext",   // html
        "shtml": "hypertext",   // html
        "sitemap": "xml",   // xml
        "slnx": "xml",   // xml
        "smd": "lisp",   // scheme
        "sml": "caml",   // caml
        "sol": "cpp",   // solidity
        "spf": "nncrontab",   // nncrontab
        "splus": "r",   // r
        "sql": "sql",   // sql
        "src": "escript",   // escript
        "srec": "srec",   // srec
        "ss": "lisp",   // scheme
        "ssh_config": "props",   // ssh_config
        "st": "smalltalk",   // smalltalk
        "sty": "latex",   // latex
        "styl": "css",   // stylus
        "stylus": "css",   // stylus
        "sv": "verilog",   // verilog
        "svelte": "hypertext",   // svelte
        "svg": "xml",   // xml
        "svh": "verilog",   // verilog
        "swift": "cpp",   // swift
        "sxbl": "xml",   // xml
        "t": "perl",   // perl
        "t2t": "txt2tags",   // txt2tags
        "t6": "raku",   // raku
        "tab": "nncrontab",   // nncrontab
        "targets": "xml",   // xml
        "tcl": "tcl",   // tcl
        "tek": "tehex",   // tehex
        "tex": "latex",   // latex
        "thy": "caml",   // caml
        "toml": "toml",   // toml
        "tpl": "hypertext",   // smarty
        "ts": "cpp",   // typescript
        "tsql": "mssql",   // mssql
        "tsv": nil,   // tsv
        "tsx": "cpp",   // typescript
        "twig": "hypertext",   // twig
        "txt": nil,   // normal
        "url": "props",   // ini
        "v": "verilog",   // verilog
        "vb": "vb",   // vb
        "vba": "vb",   // vb
        "vbproj": "xml",   // xml
        "vbs": "vb",   // vb
        "vcproj": "xml",   // xml
        "vcxproj": "xml",   // xml
        "vh": "verilog",   // verilog
        "vhd": "vhdl",   // vhdl
        "vhdl": "vhdl",   // vhdl
        "vim": "cpp",   // vimscript
        "vue": "cpp",   // javascript.js
        "wasm": "cpp",   // wasm
        "wast": "cpp",   // wat
        "wat": "cpp",   // wat
        "wer": "props",   // ini
        "wixproj": "xml",   // xml
        "wsdl": "xml",   // xml
        "wxs": "xml",   // xml
        "xaml": "xml",   // xml
        "xbl": "xml",   // xml
        "xht": "hypertext",   // html
        "xhtml": "hypertext",   // html
        "xlf": "xml",   // xml
        "xliff": "xml",   // xml
        "xml": "xml",   // xml
        "xsd": "xml",   // xml
        "xsl": "xml",   // xml
        "xslt": "xml",   // xml
        "xsml": "xml",   // xml
        "xul": "xml",   // xml
        "yaml": "yaml",   // yaml
        "yml": "yaml",   // yaml
        "zig": "cpp",   // zig
        "zsh": "bash",   // shellscript
    ]

    /// Full filenames (case-sensitive) → Lexilla lexer name.
    /// For files with no extension (Dockerfile, Makefile, etc.) and dotfiles.
    public static let byFilename: [String: String] = [
        ".bashrc": "bash",
        ".editorconfig": "props",
        ".env": "bash",
        ".gitconfig": "props",
        ".gitignore": "bash",
        ".profile": "bash",
        ".zshrc": "bash",
        "CMakeLists.txt": "cmake",
        "Dockerfile": "bash",
        "Fastfile": "ruby",
        "GNUmakefile": "makefile",
        "Gemfile": "ruby",
        "Makefile": "makefile",
        "Podfile": "ruby",
        "Rakefile": "ruby",
        "makefile": "makefile",
    ]

    /// Resolve a file URL or filename to a Lexilla lexer name.
    /// Returns `nil` if the file should be shown as plain text.
    public static func lexer(for filename: String) -> String? {
        if let exact = byFilename[filename] { return exact }
        let lower = filename.lowercased()
        if let exact = byFilename[lower] { return exact }
        // Match longest extension suffix (handles e.g. "foo.blade.php" → "blade.php").
        let parts = lower.split(separator: ".")
        if parts.count >= 3 {
            let twoDot = parts.suffix(2).joined(separator: ".")
            if let hit = byExtension[twoDot] { return hit }
        }
        if let dot = lower.lastIndex(of: ".") {
            let ext = String(lower[lower.index(after: dot)...])
            if let hit = byExtension[ext] { return hit }
        }
        return nil
    }
}
