// SPDX-License-Identifier: MIT
// Sourcepad — keyword sets per Lexilla lexer, generated by
// scripts/extract-langs.py from NPP's langs.model.xml (factual keyword
// strings only, no GPL code copied).

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

#ifdef __cplusplus
extern "C" {
#endif

/// Returns the per-slot keyword strings for the given Lexilla lexer name,
/// indexed by SCI_SETKEYWORDS slot (0 = primary, 1 = secondary, ...).
/// Empty strings indicate that slot has no keywords. Returns nil for
/// unknown lexers.
NSArray<NSString *> *_Nullable SPKeywordSetsForLexer(NSString *lexerName);

#ifdef __cplusplus
}
#endif

NS_ASSUME_NONNULL_END
